title: Zack Sifakis - Personal Website
description: PhD Student | Researcher 
author: Zack Sifakis
github_username: zacksifakis # Replace with your GitHub username
baseurl: ""
url: "https://zacksifakis.github.io/"
theme: jekyll-theme-minimal # You can choose other themes like minima, hacker, etc.
markdown: kramdown
permalink: pretty
social:
  github: https://github.com/zacksifakis
  twitter: https://twitter.com/zacksifakis