title: Zack Sifakis - Personal Website # Updated
description: PhD Student | Researcher | AI/ML # Updated
author: Zack Sifakis # Updated
github_username: zacksifakis # Updated
baseurl: "" # Keep empty for username.github.io
url: "https://zacksifakis.github.io" # Updated
# theme: jekyll-theme-minimal # Removed theme to use custom CSS
markdown: kramdown
permalink: pretty
social:
  github: https://github.com/zacksifakis # Updated
  # linkedin: https://linkedin.com/in/yourprofile # Keep placeholder or update
  twitter: https://twitter.com/zacksifakis # Keep placeholder or update